"""drop news tables (moved to news.db)

Revision ID: 001dd3eff2d1
Revises: acc72dcddeb2
Create Date: 2026-08-19 14:50:03.054584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001dd3eff2d1'
down_revision: Union[str, None] = 'acc72dcddeb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_sources')
    op.drop_index(op.f('idx_ng_created'), table_name='news_groups')
    op.drop_table('news_groups')
    op.drop_index(op.f('idx_na_group'), table_name='news_articles')
    op.drop_index(op.f('idx_na_guid'), table_name='news_articles')
    op.drop_index(op.f('idx_na_published'), table_name='news_articles')
    op.drop_index(op.f('idx_na_source'), table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_id', sa.INTEGER(), nullable=False),
    sa.Column('source_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('title', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.Column('guid', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('fetched_at', sa.DATETIME(), nullable=True),
    sa.Column('categories', sa.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_na_source'), 'news_articles', ['source_id'], unique=False)
    op.create_index(op.f('idx_na_published'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('idx_na_guid'), 'news_articles', ['guid'], unique=False)
    op.create_index(op.f('idx_na_group'), 'news_articles', ['group_id'], unique=False)
    op.create_table('news_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_ng_created'), 'news_groups', ['created_at'], unique=False)
    op.create_table('news_sources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('feed_url', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('last_fetched_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_url')
    )
    # ### end Alembic commands ###
