"""migration

Revision ID: 02098b79cd3c
Revises: 13901b7005fc
Create Date: 2026-05-01 00:49:39.588688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02098b79cd3c'
down_revision: Union[str, None] = '13901b7005fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('time_estimate', sa.Integer(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('tag',
                existing_type=sa.VARCHAR(length=50),
                type_=sa.JSON(),
                existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'tag',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('tasks', 'time_estimate')
    # ### end Alembic commands ###
