"""migration

Revision ID: 1a3a5cd0fc0f
Revises: 8b63956eaa38
Create Date: 2026-05-07 19:17:18.755371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1a3a5cd0fc0f'
down_revision: Union[str, None] = '8b63956eaa38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_created_by'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_entity_type_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_owner'), table_name='audit_log')
    op.drop_table('audit_log')
    op.add_column('article_blocks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('article_blocks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('article_blocks', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('article_blocks', sa.Column('owner', sa.String(length=100), nullable=True))
    op.add_column('articles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('articles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('articles', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('articles', sa.Column('owner', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('owner', sa.String(length=100), nullable=True))
    op.add_column('recipes', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('recipes', sa.Column('owner', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('owner', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'owner')
    op.drop_column('tasks', 'created_by')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('recipes', 'owner')
    op.drop_column('recipes', 'created_by')
    op.drop_column('products', 'owner')
    op.drop_column('products', 'created_by')
    op.drop_column('products', 'updated_at')
    op.drop_column('events', 'created_by')
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'created_at')
    op.drop_column('articles', 'owner')
    op.drop_column('articles', 'created_by')
    op.drop_column('articles', 'updated_at')
    op.drop_column('articles', 'created_at')
    op.drop_column('article_blocks', 'owner')
    op.drop_column('article_blocks', 'created_by')
    op.drop_column('article_blocks', 'updated_at')
    op.drop_column('article_blocks', 'created_at')
    op.create_table('audit_log',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=10), nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('summary', sa.VARCHAR(length=500), nullable=True),
    sa.Column('changes', sqlite.JSON(), nullable=True),
    sa.Column('extra', sqlite.JSON(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('owner', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_audit_owner'), 'audit_log', ['owner'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_entity_type_timestamp'), 'audit_log', ['entity_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_created_by'), 'audit_log', ['created_by'], unique=False)
    # ### end Alembic commands ###
