"""drop audio tables (moved to audio.db)

Revision ID: 7ae9a9c85be7
Revises: e08235e43b3a
Create Date: 2026-08-19 15:24:31.937385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae9a9c85be7'
down_revision: Union[str, None] = 'e08235e43b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_mt_album'), table_name='music_tracks')
    op.drop_index(op.f('idx_mt_artist'), table_name='music_tracks')
    op.drop_index(op.f('idx_mt_mbid'), table_name='music_tracks')
    op.drop_index(op.f('idx_mt_spotify'), table_name='music_tracks')
    op.drop_index(op.f('idx_mt_title'), table_name='music_tracks')
    op.drop_table('music_tracks')
    op.drop_index(op.f('idx_progress_audiobook'), table_name='audiobooks_progress')
    op.drop_table('audiobooks_progress')
    op.drop_index(op.f('idx_audiobook_asin'), table_name='audiobooks_media')
    op.drop_index(op.f('idx_audiobook_author'), table_name='audiobooks_media')
    op.drop_index(op.f('idx_audiobook_title'), table_name='audiobooks_media')
    op.drop_table('audiobooks_media')
    op.drop_index(op.f('idx_chapter_audiobook'), table_name='audiobooks_chapters')
    op.drop_table('audiobooks_chapters')
    op.drop_index(op.f('idx_episode_podcast'), table_name='podcasts_episodes')
    op.drop_index(op.f('idx_episode_published'), table_name='podcasts_episodes')
    op.drop_table('podcasts_episodes')
    op.drop_index(op.f('idx_podcast_index_id'), table_name='podcasts_media')
    op.drop_index(op.f('idx_podcast_title'), table_name='podcasts_media')
    op.drop_table('podcasts_media')
    op.drop_index(op.f('idx_me_artist'), table_name='music_events')
    op.drop_index(op.f('idx_me_date'), table_name='music_events')
    op.drop_index(op.f('idx_me_type'), table_name='music_events')
    op.drop_table('music_events')
    op.drop_index(op.f('idx_progress_episode'), table_name='podcasts_progress')
    op.drop_index(op.f('idx_progress_listened'), table_name='podcasts_progress')
    op.drop_table('podcasts_progress')
    op.drop_table('music_playlists')
    op.drop_index(op.f('idx_mpi_playlist'), table_name='music_playlist_items')
    op.drop_index(op.f('idx_mpi_track'), table_name='music_playlist_items')
    op.drop_table('music_playlist_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_playlist_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('playlist_id', sa.INTEGER(), nullable=False),
    sa.Column('track_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['music_playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['music_tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_mpi_track'), 'music_playlist_items', ['track_id'], unique=False)
    op.create_index(op.f('idx_mpi_playlist'), 'music_playlist_items', ['playlist_id'], unique=False)
    op.create_table('music_playlists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('podcasts_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('episode_id', sa.INTEGER(), nullable=False),
    sa.Column('position_ms', sa.BIGINT(), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=False),
    sa.Column('last_listened_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['podcasts_episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id')
    )
    op.create_index(op.f('idx_progress_listened'), 'podcasts_progress', ['last_listened_at'], unique=False)
    op.create_index(op.f('idx_progress_episode'), 'podcasts_progress', ['episode_id'], unique=False)
    op.create_table('music_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('artist', sa.VARCHAR(length=500), nullable=True),
    sa.Column('venue', sa.VARCHAR(length=500), nullable=True),
    sa.Column('city', sa.VARCHAR(length=200), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('cover_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_me_type'), 'music_events', ['event_type'], unique=False)
    op.create_index(op.f('idx_me_date'), 'music_events', ['date'], unique=False)
    op.create_index(op.f('idx_me_artist'), 'music_events', ['artist'], unique=False)
    op.create_table('podcasts_media',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('author', sa.VARCHAR(length=500), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('cover_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('feed_url', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('podcast_index_id', sa.INTEGER(), nullable=True),
    sa.Column('last_fetched_at', sa.DATETIME(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_url')
    )
    op.create_index(op.f('idx_podcast_title'), 'podcasts_media', ['title'], unique=False)
    op.create_index(op.f('idx_podcast_index_id'), 'podcasts_media', ['podcast_index_id'], unique=False)
    op.create_table('podcasts_episodes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('podcast_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('audio_url', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('duration_ms', sa.BIGINT(), nullable=True),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.Column('episode_number', sa.INTEGER(), nullable=True),
    sa.Column('season_number', sa.INTEGER(), nullable=True),
    sa.Column('guid', sa.VARCHAR(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcasts_media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('podcast_id', 'guid', name=op.f('uq_episode_guid_per_podcast'))
    )
    op.create_index(op.f('idx_episode_published'), 'podcasts_episodes', ['published_at'], unique=False)
    op.create_index(op.f('idx_episode_podcast'), 'podcasts_episodes', ['podcast_id'], unique=False)
    op.create_table('audiobooks_chapters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('audiobook_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=True),
    sa.Column('start_ms', sa.BIGINT(), nullable=False),
    sa.Column('end_ms', sa.BIGINT(), nullable=True),
    sa.Column('chapter_number', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks_media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_chapter_audiobook'), 'audiobooks_chapters', ['audiobook_id'], unique=False)
    op.create_table('audiobooks_media',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('author', sa.VARCHAR(length=500), nullable=True),
    sa.Column('narrator', sa.VARCHAR(length=500), nullable=True),
    sa.Column('duration_ms', sa.BIGINT(), nullable=True),
    sa.Column('asin', sa.VARCHAR(length=50), nullable=True),
    sa.Column('audnexus_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cover_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('chapter_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asin')
    )
    op.create_index(op.f('idx_audiobook_title'), 'audiobooks_media', ['title'], unique=False)
    op.create_index(op.f('idx_audiobook_author'), 'audiobooks_media', ['author'], unique=False)
    op.create_index(op.f('idx_audiobook_asin'), 'audiobooks_media', ['asin'], unique=False)
    op.create_table('audiobooks_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('audiobook_id', sa.INTEGER(), nullable=False),
    sa.Column('position_ms', sa.BIGINT(), nullable=False),
    sa.Column('chapter_number', sa.INTEGER(), nullable=True),
    sa.Column('last_listened_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks_media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audiobook_id')
    )
    op.create_index(op.f('idx_progress_audiobook'), 'audiobooks_progress', ['audiobook_id'], unique=False)
    op.create_table('music_tracks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('artist', sa.VARCHAR(length=500), nullable=True),
    sa.Column('album', sa.VARCHAR(length=500), nullable=True),
    sa.Column('album_artist', sa.VARCHAR(length=500), nullable=True),
    sa.Column('track_number', sa.INTEGER(), nullable=True),
    sa.Column('disc_number', sa.INTEGER(), nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), nullable=True),
    sa.Column('genre', sa.VARCHAR(length=200), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('musicbrainz_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('spotify_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cover_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('play_count', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('last_played_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_mt_title'), 'music_tracks', ['title'], unique=False)
    op.create_index(op.f('idx_mt_spotify'), 'music_tracks', ['spotify_id'], unique=False)
    op.create_index(op.f('idx_mt_mbid'), 'music_tracks', ['musicbrainz_id'], unique=False)
    op.create_index(op.f('idx_mt_artist'), 'music_tracks', ['artist'], unique=False)
    op.create_index(op.f('idx_mt_album'), 'music_tracks', ['album'], unique=False)
    # ### end Alembic commands ###
