"""migration

Revision ID: 8b63956eaa38
Revises: 02098b79cd3c
Create Date: 2026-05-01 01:31:10.785495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b63956eaa38'
down_revision: Union[str, None] = '02098b79cd3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('datetime_started', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('datetime_completed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'datetime_completed')
    op.drop_column('tasks', 'datetime_started')
    # ### end Alembic commands ###
