"""migration

Revision ID: a7284a96501d
Revises: bec2ddf0888d
Create Date: 2026-05-01 00:03:22.722301

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a7284a96501d"
down_revision: Union[str, None] = "bec2ddf0888d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.drop_column("tasks", "time_slot")
    op.drop_column("tasks", "tag")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tag", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("time_slot", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "time_slot")
    op.drop_column("tasks", "tag")
    # ### end Alembic commands ###
