"""migration

Revision ID: ab39604ea673
Revises: 1a3a5cd0fc0f
Create Date: 2026-05-07 21:39:52.909219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ab39604ea673'
down_revision: Union[str, None] = '1a3a5cd0fc0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_created_by'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_entity_type_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_owner'), table_name='audit_log')
    op.drop_table('audit_log')
    op.add_column('events', sa.Column('google_event_id', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('source', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_events_google_event_id'), 'events', ['google_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_google_event_id'), table_name='events')
    op.drop_column('events', 'source')
    op.drop_column('events', 'google_event_id')
    op.create_table('audit_log',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=10), nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('summary', sa.VARCHAR(length=500), nullable=True),
    sa.Column('changes', sqlite.JSON(), nullable=True),
    sa.Column('extra', sqlite.JSON(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('owner', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_audit_owner'), 'audit_log', ['owner'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_entity_type_timestamp'), 'audit_log', ['entity_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_created_by'), 'audit_log', ['created_by'], unique=False)
    # ### end Alembic commands ###
