"""ingredient image

Revision ID: acc72dcddeb2
Revises: 30c04d06922e
Create Date: 2026-08-17 21:56:17.686293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc72dcddeb2'
down_revision: Union[str, None] = '30c04d06922e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'image')
    # ### end Alembic commands ###
