"""migration

Revision ID: c386a5e9363e
Revises: ab39604ea673
Create Date: 2026-05-07 23:59:29.270435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c386a5e9363e'
down_revision: Union[str, None] = 'ab39604ea673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_created_by'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_entity_type_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_owner'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=10), nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('summary', sa.VARCHAR(length=500), nullable=True),
    sa.Column('changes', sqlite.JSON(), nullable=True),
    sa.Column('extra', sqlite.JSON(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('owner', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_audit_owner'), 'audit_log', ['owner'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_entity_type_timestamp'), 'audit_log', ['entity_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_created_by'), 'audit_log', ['created_by'], unique=False)
    # ### end Alembic commands ###
