"""drop recipe tables (moved to recipes.db)

Revision ID: e08235e43b3a
Revises: 001dd3eff2d1
Create Date: 2026-08-19 15:10:17.069120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e08235e43b3a'
down_revision: Union[str, None] = '001dd3eff2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usda_foods')
    op.drop_table('utensils')
    op.drop_table('recipes')
    op.drop_table('recipe_categories')
    op.drop_table('ingredients')
    op.drop_table('users')
    op.drop_table('substitutions')
    op.drop_table('recipe_ingredients')
    op.drop_table('recipe_allergens')
    op.drop_table('recipe_utensils')
    op.drop_table('categories')
    op.drop_table('allergens')
    op.drop_table('ingredient_compositions')
    op.drop_table('unit_conversions')
    # ingredient_product_mapping.ingredient_id had an unnamed FK to
    # `ingredients`, which now lives in recipes.db (a separate database) and
    # can no longer be referenced. The table is empty, so recreate it
    # directly instead of trying to name-match the anonymous FK in batch
    # mode.
    op.drop_table('ingredient_product_mapping')
    op.create_table(
        'ingredient_product_mapping',
        sa.Column('_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('ingredient_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products._id'], ),
        sa.PrimaryKeyConstraint('_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient_product_mapping')
    op.create_table('unit_conversions',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('from_unit', sa.VARCHAR(length=50), nullable=False),
    sa.Column('to_unit', sa.VARCHAR(length=50), nullable=False),
    sa.Column('conversion_factor', sa.FLOAT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.Column('is_volume', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('ingredient_compositions',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), nullable=True),
    sa.Column('kind', sa.VARCHAR(length=50), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=50), nullable=True),
    sa.Column('daily_value', sa.FLOAT(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients._id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes._id'], name=op.f('recipe_id_foreign_const')),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('allergens',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('categories',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipe_utensils',
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('utensil_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes._id'], ),
    sa.ForeignKeyConstraint(['utensil_id'], ['utensils._id'], )
    )
    op.create_table('recipe_allergens',
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('allergen_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens._id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes._id'], )
    )
    op.create_table('recipe_ingredients',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), nullable=False),
    sa.Column('product', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ingredient_recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('fdc_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients._id'], ),
    sa.ForeignKeyConstraint(['ingredient_recipe_id'], ['recipes._id'], name=op.f('foreign_key_ingredient_recipe')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('substitutions',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=50), nullable=True),
    sa.Column('original', sa.VARCHAR(length=50), nullable=False),
    sa.Column('replacement', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ratio', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('users',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ingredients',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('calories', sa.FLOAT(), nullable=True),
    sa.Column('density', sa.FLOAT(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.Column('composition', sqlite.JSON(), nullable=True),
    sa.Column('price_high', sa.FLOAT(), nullable=True),
    sa.Column('price_low', sa.FLOAT(), nullable=True),
    sa.Column('price_medium', sa.FLOAT(), nullable=True),
    sa.Column('unit_metric', sa.VARCHAR(length=50), nullable=True),
    sa.Column('unit_us_customary', sa.VARCHAR(length=50), nullable=True),
    sa.Column('unit_us_legal', sa.VARCHAR(length=50), nullable=True),
    sa.Column('unit_canada', sa.VARCHAR(length=50), nullable=True),
    sa.Column('unit_australia', sa.VARCHAR(length=50), nullable=True),
    sa.Column('unit_uk', sa.VARCHAR(length=50), nullable=True),
    sa.Column('item_avg_weight', sa.FLOAT(), nullable=True),
    sa.Column('fdc_id', sa.INTEGER(), nullable=True),
    sa.Column('image', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipe_categories',
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories._id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes._id'], )
    )
    op.create_table('recipes',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('images', sqlite.JSON(), nullable=True),
    sa.Column('instructions', sqlite.JSON(), nullable=False),
    sa.Column('prep_time', sa.INTEGER(), nullable=True),
    sa.Column('cook_time', sa.INTEGER(), nullable=True),
    sa.Column('servings', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.Column('component', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('owner', sa.VARCHAR(length=100), nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('source_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('external_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('synced_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_recipe_source_external_id'))
    )
    op.create_table('utensils',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('usda_foods',
    sa.Column('fdc_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('fdc_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table(
        'ingredient_product_mapping',
        sa.Column('_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('ingredient_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products._id'], ),
        sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients._id'], ),
        sa.PrimaryKeyConstraint('_id'),
    )
    # ### end Alembic commands ###
