"""migration

Revision ID: e26514f50915
Revises: faab5a311211
Create Date: 2026-05-19 14:17:32.486100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26514f50915'
down_revision: Union[str, None] = 'faab5a311211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('image_url', sa.String(length=2000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('guid', sa.String(length=2000), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_na_group', 'news_articles', ['group_id'], unique=False)
    op.create_index('idx_na_guid', 'news_articles', ['guid'], unique=False)
    op.create_index('idx_na_published', 'news_articles', ['published_at'], unique=False)
    op.create_index('idx_na_source', 'news_articles', ['source_id'], unique=False)
    op.create_table('news_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ng_created', 'news_groups', ['created_at'], unique=False)
    op.create_table('news_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('feed_url', sa.String(length=2000), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_sources')
    op.drop_index('idx_ng_created', table_name='news_groups')
    op.drop_table('news_groups')
    op.drop_index('idx_na_source', table_name='news_articles')
    op.drop_index('idx_na_published', table_name='news_articles')
    op.drop_index('idx_na_guid', table_name='news_articles')
    op.drop_index('idx_na_group', table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
