"""drop health tables (moved to private/health.db)

Revision ID: e7f2010fcb48
Revises: f93d969f01be
Create Date: 2026-08-19 15:39:25.549394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e7f2010fcb48'
down_revision: Union[str, None] = 'f93d969f01be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ha_source'), table_name='health_activities')
    op.drop_index(op.f('idx_ha_type_start'), table_name='health_activities')
    op.drop_table('health_activities')
    op.drop_table('health_connectors')
    op.drop_index(op.f('idx_hds_day'), table_name='health_daily_summaries')
    op.drop_table('health_daily_summaries')
    op.drop_index(op.f('idx_hm_source'), table_name='health_metrics')
    op.drop_index(op.f('idx_hm_type_ts'), table_name='health_metrics')
    op.drop_table('health_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_metrics',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('metric_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), nullable=True),
    sa.Column('device', sa.VARCHAR(length=100), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('source', 'metric_type', 'timestamp', name=op.f('uq_health_metric_dedup'))
    )
    op.create_index(op.f('idx_hm_type_ts'), 'health_metrics', ['metric_type', 'timestamp'], unique=False)
    op.create_index(op.f('idx_hm_source'), 'health_metrics', ['source'], unique=False)
    op.create_table('health_daily_summaries',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('day', sa.DATE(), nullable=False),
    sa.Column('steps', sa.INTEGER(), nullable=True),
    sa.Column('steps_goal', sa.INTEGER(), nullable=True),
    sa.Column('distance_m', sa.FLOAT(), nullable=True),
    sa.Column('floors_ascended', sa.INTEGER(), nullable=True),
    sa.Column('floors_descended', sa.INTEGER(), nullable=True),
    sa.Column('calories_total', sa.INTEGER(), nullable=True),
    sa.Column('calories_active', sa.INTEGER(), nullable=True),
    sa.Column('calories_resting', sa.INTEGER(), nullable=True),
    sa.Column('hr_min', sa.INTEGER(), nullable=True),
    sa.Column('hr_max', sa.INTEGER(), nullable=True),
    sa.Column('hr_resting', sa.INTEGER(), nullable=True),
    sa.Column('stress_avg', sa.INTEGER(), nullable=True),
    sa.Column('stress_max', sa.INTEGER(), nullable=True),
    sa.Column('bb_min', sa.INTEGER(), nullable=True),
    sa.Column('bb_max', sa.INTEGER(), nullable=True),
    sa.Column('bb_charged', sa.INTEGER(), nullable=True),
    sa.Column('bb_drained', sa.INTEGER(), nullable=True),
    sa.Column('bb_latest', sa.INTEGER(), nullable=True),
    sa.Column('rr_avg', sa.FLOAT(), nullable=True),
    sa.Column('rr_min', sa.FLOAT(), nullable=True),
    sa.Column('rr_max', sa.FLOAT(), nullable=True),
    sa.Column('intensity_moderate', sa.INTEGER(), nullable=True),
    sa.Column('intensity_vigorous', sa.INTEGER(), nullable=True),
    sa.Column('intensity_goal', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('hydration_ml', sa.INTEGER(), nullable=True),
    sa.Column('spo2_avg', sa.FLOAT(), nullable=True),
    sa.Column('spo2_min', sa.FLOAT(), nullable=True),
    sa.Column('sleep_seconds', sa.INTEGER(), nullable=True),
    sa.Column('sleep_score', sa.INTEGER(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('source', 'day', name=op.f('uq_health_daily_dedup'))
    )
    op.create_index(op.f('idx_hds_day'), 'health_daily_summaries', ['day'], unique=False)
    op.create_table('health_connectors',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('config', sqlite.JSON(), nullable=True),
    sa.Column('last_sync', sa.DATETIME(), nullable=True),
    sa.Column('last_error', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('health_activities',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('activity_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), nullable=True),
    sa.Column('distance_m', sa.FLOAT(), nullable=True),
    sa.Column('calories', sa.FLOAT(), nullable=True),
    sa.Column('avg_hr', sa.FLOAT(), nullable=True),
    sa.Column('max_hr', sa.FLOAT(), nullable=True),
    sa.Column('min_hr', sa.FLOAT(), nullable=True),
    sa.Column('summary', sqlite.JSON(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('source', 'source_id', name=op.f('uq_health_activity_dedup'))
    )
    op.create_index(op.f('idx_ha_type_start'), 'health_activities', ['activity_type', 'start_time'], unique=False)
    op.create_index(op.f('idx_ha_source'), 'health_activities', ['source'], unique=False)
    # ### end Alembic commands ###
