"""drop calendar and articles tables (moved to calendar.db and articles.db)

Revision ID: ee73a2672163
Revises: e7f2010fcb48
Create Date: 2026-08-19 16:01:33.833639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ee73a2672163'
down_revision: Union[str, None] = 'e7f2010fcb48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_index(op.f('ix_events_google_event_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('articles')
    op.drop_table('article_blocks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_blocks',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('page_id', sa.INTEGER(), nullable=True),
    sa.Column('parent', sa.INTEGER(), nullable=True),
    sa.Column('kind', sa.VARCHAR(length=25), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.Column('sequence', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('owner', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['articles._id'], ),
    sa.ForeignKeyConstraint(['parent'], ['article_blocks._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('articles',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('root_id', sa.INTEGER(), nullable=True),
    sa.Column('parent', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('namespace', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.Column('sequence', sa.FLOAT(), nullable=True),
    sa.Column('public', sa.BOOLEAN(), nullable=True),
    sa.Column('article_kind', sa.VARCHAR(length=25), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('owner', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['articles._id'], ),
    sa.ForeignKeyConstraint(['root_id'], ['articles._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('events',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('kind', sa.INTEGER(), nullable=True),
    sa.Column('color', sa.VARCHAR(length=7), nullable=True),
    sa.Column('datetime_start', sa.DATETIME(), nullable=False),
    sa.Column('datetime_end', sa.DATETIME(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('guests', sqlite.JSON(), nullable=True),
    sa.Column('task', sa.INTEGER(), nullable=True),
    sa.Column('done', sa.BOOLEAN(), nullable=True),
    sa.Column('price_budget', sa.FLOAT(), nullable=True),
    sa.Column('price_real', sa.FLOAT(), nullable=True),
    sa.Column('people_count', sa.INTEGER(), nullable=True),
    sa.Column('template', sa.BOOLEAN(), nullable=True),
    sa.Column('recuring', sa.BOOLEAN(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.Column('owner', sa.VARCHAR(length=200), nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('google_event_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['task'], ['tasks._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_events_google_event_id'), 'events', ['google_event_id'], unique=False)
    op.create_table('tasks',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('datetime_deadline', sa.DATETIME(), nullable=True),
    sa.Column('done', sa.BOOLEAN(), nullable=True),
    sa.Column('price_budget', sa.FLOAT(), nullable=True),
    sa.Column('price_real', sa.FLOAT(), nullable=True),
    sa.Column('people_count', sa.INTEGER(), nullable=True),
    sa.Column('template', sa.BOOLEAN(), nullable=True),
    sa.Column('recuring', sa.BOOLEAN(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('extension', sqlite.JSON(), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('datetime_done', sa.DATETIME(), nullable=True),
    sa.Column('root_id', sa.INTEGER(), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('tag', sqlite.JSON(), nullable=True),
    sa.Column('time_slot', sa.VARCHAR(length=50), nullable=True),
    sa.Column('periodicity', sa.VARCHAR(length=50), nullable=True),
    sa.Column('time_estimate', sa.INTEGER(), nullable=True),
    sa.Column('datetime_started', sa.DATETIME(), nullable=True),
    sa.Column('datetime_completed', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('owner', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###
