"""drop shows tables (moved to video.db)

Revision ID: f93d969f01be
Revises: 7ae9a9c85be7
Create Date: 2026-08-19 15:33:07.060598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f93d969f01be'
down_revision: Union[str, None] = '7ae9a9c85be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ci_collection'), table_name='shows_collection_items')
    op.drop_table('shows_collection_items')
    op.drop_table('shows_collections')
    op.drop_index(op.f('idx_wh_media'), table_name='shows_watch_history')
    op.drop_index(op.f('idx_wh_watched_at'), table_name='shows_watch_history')
    op.drop_table('shows_watch_history')
    op.drop_index(op.f('idx_media_title'), table_name='shows_media')
    op.drop_index(op.f('idx_media_tmdb'), table_name='shows_media')
    op.drop_table('shows_media')
    op.drop_table('shows_user_ratings')
    op.drop_index(op.f('idx_watchlist_rank'), table_name='shows_watchlist')
    op.drop_table('shows_watchlist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows_watchlist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('media_id', sa.INTEGER(), nullable=False),
    sa.Column('rank', sa.INTEGER(), nullable=True),
    sa.Column('listed_at', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['shows_media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id')
    )
    op.create_index(op.f('idx_watchlist_rank'), 'shows_watchlist', ['rank'], unique=False)
    op.create_table('shows_user_ratings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('media_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('rated_at', sa.DATETIME(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['shows_media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id')
    )
    op.create_table('shows_media',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('media_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=500), nullable=True),
    sa.Column('trakt_id', sa.INTEGER(), nullable=True),
    sa.Column('tmdb_id', sa.INTEGER(), nullable=True),
    sa.Column('imdb_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('tvdb_id', sa.INTEGER(), nullable=True),
    sa.Column('genres', sqlite.JSON(), nullable=True),
    sa.Column('country', sa.VARCHAR(length=10), nullable=True),
    sa.Column('runtime', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('overview', sa.TEXT(), nullable=True),
    sa.Column('poster_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('backdrop_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('user_status', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_type', 'trakt_id', name='uq_media_trakt')
    )
    op.create_index(op.f('idx_media_tmdb'), 'shows_media', ['media_type', 'tmdb_id'], unique=False)
    op.create_index(op.f('idx_media_title'), 'shows_media', ['title'], unique=False)
    op.create_table('shows_watch_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('media_id', sa.INTEGER(), nullable=False),
    sa.Column('watched_at', sa.DATETIME(), nullable=False),
    sa.Column('season', sa.INTEGER(), nullable=True),
    sa.Column('episode', sa.INTEGER(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['shows_media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'watched_at', 'season', 'episode', 'source', name=op.f('uq_watch_history_dedup'))
    )
    op.create_index(op.f('idx_wh_watched_at'), 'shows_watch_history', ['watched_at'], unique=False)
    op.create_index(op.f('idx_wh_media'), 'shows_watch_history', ['media_id'], unique=False)
    op.create_table('shows_collections',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('collection_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shows_collection_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('collection_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('media_id', sa.INTEGER(), nullable=False),
    sa.Column('rank', sa.INTEGER(), nullable=True),
    sa.Column('added_at', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['shows_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['shows_media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'media_id', name=op.f('uq_collection_media'))
    )
    op.create_index(op.f('idx_ci_collection'), 'shows_collection_items', ['collection_id'], unique=False)
    # ### end Alembic commands ###
