"""baseline

Revision ID: 10ea86ba786c
Revises: 
Create Date: 2026-08-19 16:05:59.617091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ea86ba786c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergens',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extension', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('categories',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extension', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredients',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fdc_id', sa.Integer(), nullable=True),
    sa.Column('price_high', sa.Float(), nullable=True),
    sa.Column('price_low', sa.Float(), nullable=True),
    sa.Column('price_medium', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('composition', sa.JSON(), nullable=True),
    sa.Column('extension', sa.JSON(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('item_avg_weight', sa.Float(), nullable=True),
    sa.Column('unit_metric', sa.String(length=50), nullable=True),
    sa.Column('unit_us_customary', sa.String(length=50), nullable=True),
    sa.Column('unit_us_legal', sa.String(length=50), nullable=True),
    sa.Column('unit_canada', sa.String(length=50), nullable=True),
    sa.Column('unit_australia', sa.String(length=50), nullable=True),
    sa.Column('unit_uk', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('substitutions',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('original', sa.String(length=50), nullable=False),
    sa.Column('replacement', sa.String(length=50), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('usda_foods',
    sa.Column('fdc_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('fdc_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('utensils',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extension', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipes',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('instructions', sa.JSON(), nullable=False),
    sa.Column('prep_time', sa.Integer(), nullable=True),
    sa.Column('cook_time', sa.Integer(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('component', sa.Boolean(), nullable=True),
    sa.Column('extension', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_recipe_source_external_id')
    )
    op.create_table('unit_conversions',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('from_unit', sa.String(length=50), nullable=False),
    sa.Column('to_unit', sa.String(length=50), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_volume', sa.Boolean(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('extension', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('ingredient_compositions',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('daily_value', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('extension', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients._id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('recipe_allergens',
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('allergen_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens._id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes._id'], )
    )
    op.create_table('recipe_categories',
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories._id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes._id'], )
    )
    op.create_table('recipe_ingredients',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_recipe_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('fdc_id', sa.Integer(), nullable=True),
    sa.Column('product', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients._id'], ),
    sa.ForeignKeyConstraint(['ingredient_recipe_id'], ['recipes._id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('recipe_utensils',
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('utensil_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes._id'], ),
    sa.ForeignKeyConstraint(['utensil_id'], ['utensils._id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_utensils')
    op.drop_table('recipe_ingredients')
    op.drop_table('recipe_categories')
    op.drop_table('recipe_allergens')
    op.drop_table('ingredient_compositions')
    op.drop_table('unit_conversions')
    op.drop_table('recipes')
    op.drop_table('utensils')
    op.drop_table('users')
    op.drop_table('usda_foods')
    op.drop_table('substitutions')
    op.drop_table('ingredients')
    op.drop_table('categories')
    op.drop_table('allergens')
    # ### end Alembic commands ###
