"""baseline

Revision ID: abb17c79ebeb
Revises: 
Create Date: 2026-08-19 16:06:18.528511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb17c79ebeb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiobooks_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('narrator', sa.String(length=500), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('asin', sa.String(length=50), nullable=True),
    sa.Column('audnexus_id', sa.String(length=100), nullable=True),
    sa.Column('cover_path', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chapter_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asin')
    )
    op.create_index('idx_audiobook_asin', 'audiobooks_media', ['asin'], unique=False)
    op.create_index('idx_audiobook_author', 'audiobooks_media', ['author'], unique=False)
    op.create_index('idx_audiobook_title', 'audiobooks_media', ['title'], unique=False)
    op.create_table('music_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('artist', sa.String(length=500), nullable=True),
    sa.Column('venue', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('cover_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_me_artist', 'music_events', ['artist'], unique=False)
    op.create_index('idx_me_date', 'music_events', ['date'], unique=False)
    op.create_index('idx_me_type', 'music_events', ['event_type'], unique=False)
    op.create_table('music_playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('artist', sa.String(length=500), nullable=True),
    sa.Column('album', sa.String(length=500), nullable=True),
    sa.Column('album_artist', sa.String(length=500), nullable=True),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('disc_number', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=200), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('musicbrainz_id', sa.String(length=36), nullable=True),
    sa.Column('spotify_id', sa.String(length=100), nullable=True),
    sa.Column('cover_path', sa.String(length=500), nullable=True),
    sa.Column('play_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_played_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mt_album', 'music_tracks', ['album'], unique=False)
    op.create_index('idx_mt_artist', 'music_tracks', ['artist'], unique=False)
    op.create_index('idx_mt_mbid', 'music_tracks', ['musicbrainz_id'], unique=False)
    op.create_index('idx_mt_spotify', 'music_tracks', ['spotify_id'], unique=False)
    op.create_index('idx_mt_title', 'music_tracks', ['title'], unique=False)
    op.create_table('podcasts_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_path', sa.String(length=500), nullable=True),
    sa.Column('feed_url', sa.String(length=2000), nullable=False),
    sa.Column('podcast_index_id', sa.Integer(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_url')
    )
    op.create_index('idx_podcast_index_id', 'podcasts_media', ['podcast_index_id'], unique=False)
    op.create_index('idx_podcast_title', 'podcasts_media', ['title'], unique=False)
    op.create_table('audiobooks_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audiobook_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('start_ms', sa.BigInteger(), nullable=False),
    sa.Column('end_ms', sa.BigInteger(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks_media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chapter_audiobook', 'audiobooks_chapters', ['audiobook_id'], unique=False)
    op.create_table('audiobooks_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audiobook_id', sa.Integer(), nullable=False),
    sa.Column('position_ms', sa.BigInteger(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('last_listened_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks_media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audiobook_id')
    )
    op.create_index('idx_progress_audiobook', 'audiobooks_progress', ['audiobook_id'], unique=False)
    op.create_table('music_playlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['music_playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['music_tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mpi_playlist', 'music_playlist_items', ['playlist_id'], unique=False)
    op.create_index('idx_mpi_track', 'music_playlist_items', ['track_id'], unique=False)
    op.create_table('podcasts_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('podcast_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=2000), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('guid', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcasts_media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('podcast_id', 'guid', name='uq_episode_guid_per_podcast')
    )
    op.create_index('idx_episode_podcast', 'podcasts_episodes', ['podcast_id'], unique=False)
    op.create_index('idx_episode_published', 'podcasts_episodes', ['published_at'], unique=False)
    op.create_table('podcasts_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('position_ms', sa.BigInteger(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('last_listened_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['podcasts_episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id')
    )
    op.create_index('idx_progress_episode', 'podcasts_progress', ['episode_id'], unique=False)
    op.create_index('idx_progress_listened', 'podcasts_progress', ['last_listened_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_progress_listened', table_name='podcasts_progress')
    op.drop_index('idx_progress_episode', table_name='podcasts_progress')
    op.drop_table('podcasts_progress')
    op.drop_index('idx_episode_published', table_name='podcasts_episodes')
    op.drop_index('idx_episode_podcast', table_name='podcasts_episodes')
    op.drop_table('podcasts_episodes')
    op.drop_index('idx_mpi_track', table_name='music_playlist_items')
    op.drop_index('idx_mpi_playlist', table_name='music_playlist_items')
    op.drop_table('music_playlist_items')
    op.drop_index('idx_progress_audiobook', table_name='audiobooks_progress')
    op.drop_table('audiobooks_progress')
    op.drop_index('idx_chapter_audiobook', table_name='audiobooks_chapters')
    op.drop_table('audiobooks_chapters')
    op.drop_index('idx_podcast_title', table_name='podcasts_media')
    op.drop_index('idx_podcast_index_id', table_name='podcasts_media')
    op.drop_table('podcasts_media')
    op.drop_index('idx_mt_title', table_name='music_tracks')
    op.drop_index('idx_mt_spotify', table_name='music_tracks')
    op.drop_index('idx_mt_mbid', table_name='music_tracks')
    op.drop_index('idx_mt_artist', table_name='music_tracks')
    op.drop_index('idx_mt_album', table_name='music_tracks')
    op.drop_table('music_tracks')
    op.drop_table('music_playlists')
    op.drop_index('idx_me_type', table_name='music_events')
    op.drop_index('idx_me_date', table_name='music_events')
    op.drop_index('idx_me_artist', table_name='music_events')
    op.drop_table('music_events')
    op.drop_index('idx_audiobook_title', table_name='audiobooks_media')
    op.drop_index('idx_audiobook_author', table_name='audiobooks_media')
    op.drop_index('idx_audiobook_asin', table_name='audiobooks_media')
    op.drop_table('audiobooks_media')
    # ### end Alembic commands ###
