"""baseline

Revision ID: b98a5e456f24
Revises: 
Create Date: 2026-08-19 16:07:39.403188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98a5e456f24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('extension', sa.JSON(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('article_kind', sa.String(length=25), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['articles._id'], ),
    sa.ForeignKeyConstraint(['root_id'], ['articles._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('article_blocks',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Float(), nullable=True),
    sa.Column('kind', sa.String(length=25), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('extension', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['articles._id'], ),
    sa.ForeignKeyConstraint(['parent'], ['article_blocks._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_blocks')
    op.drop_table('articles')
    # ### end Alembic commands ###
