"""baseline

Revision ID: e1c6dc4af4bd
Revises: 
Create Date: 2026-08-19 16:06:56.559121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c6dc4af4bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_activities',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('min_hr', sa.Float(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('extension', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_health_activity_dedup')
    )
    op.create_index('idx_ha_source', 'health_activities', ['source'], unique=False)
    op.create_index('idx_ha_type_start', 'health_activities', ['activity_type', 'start_time'], unique=False)
    op.create_table('health_connectors',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('health_daily_summaries',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('steps_goal', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('floors_ascended', sa.Integer(), nullable=True),
    sa.Column('floors_descended', sa.Integer(), nullable=True),
    sa.Column('calories_total', sa.Integer(), nullable=True),
    sa.Column('calories_active', sa.Integer(), nullable=True),
    sa.Column('calories_resting', sa.Integer(), nullable=True),
    sa.Column('hr_min', sa.Integer(), nullable=True),
    sa.Column('hr_max', sa.Integer(), nullable=True),
    sa.Column('hr_resting', sa.Integer(), nullable=True),
    sa.Column('stress_avg', sa.Integer(), nullable=True),
    sa.Column('stress_max', sa.Integer(), nullable=True),
    sa.Column('bb_min', sa.Integer(), nullable=True),
    sa.Column('bb_max', sa.Integer(), nullable=True),
    sa.Column('bb_charged', sa.Integer(), nullable=True),
    sa.Column('bb_drained', sa.Integer(), nullable=True),
    sa.Column('bb_latest', sa.Integer(), nullable=True),
    sa.Column('rr_avg', sa.Float(), nullable=True),
    sa.Column('rr_min', sa.Float(), nullable=True),
    sa.Column('rr_max', sa.Float(), nullable=True),
    sa.Column('intensity_moderate', sa.Integer(), nullable=True),
    sa.Column('intensity_vigorous', sa.Integer(), nullable=True),
    sa.Column('intensity_goal', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('hydration_ml', sa.Integer(), nullable=True),
    sa.Column('spo2_avg', sa.Float(), nullable=True),
    sa.Column('spo2_min', sa.Float(), nullable=True),
    sa.Column('sleep_seconds', sa.Integer(), nullable=True),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('extension', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('source', 'day', name='uq_health_daily_dedup')
    )
    op.create_index('idx_hds_day', 'health_daily_summaries', ['day'], unique=False)
    op.create_table('health_metrics',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('extension', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('source', 'metric_type', 'timestamp', name='uq_health_metric_dedup')
    )
    op.create_index('idx_hm_source', 'health_metrics', ['source'], unique=False)
    op.create_index('idx_hm_type_ts', 'health_metrics', ['metric_type', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hm_type_ts', table_name='health_metrics')
    op.drop_index('idx_hm_source', table_name='health_metrics')
    op.drop_table('health_metrics')
    op.drop_index('idx_hds_day', table_name='health_daily_summaries')
    op.drop_table('health_daily_summaries')
    op.drop_table('health_connectors')
    op.drop_index('idx_ha_type_start', table_name='health_activities')
    op.drop_index('idx_ha_source', table_name='health_activities')
    op.drop_table('health_activities')
    # ### end Alembic commands ###
