

import logging

from telegram import Update, InlineKeyboardMarkup, InlineKeyboardButton, BotCommand
from telegram.ext import Application, Updater, MessageHandler, CommandHandler, filters, CallbackContext, CallbackQueryHandler
import json
import hashlib
import os
import sqlite3
import asyncio
import re

DB_NAME = './todo.sqlite3'

CHECK_CHAR = '✅'
UNCHECK_CHAR = '⬜'

def gen_db():
    # table: Replies
    # message_and_chat_id, reply_id, created_at
    # unique index on message_id
    with sqlite3.connect(DB_NAME) as db:
        db.execute('''
            CREATE TABLE IF NOT EXISTS Replies (
                message_and_chat_id VARCHAR(255) NOT NULL,
                reply_and_chat_id VARCHAR(255) NOT NULL,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                state TEXT,
                PRIMARY KEY (message_and_chat_id),
                UNIQUE (reply_and_chat_id)
            )
        ''')

        # store mode for each chat
        db.execute('''
            CREATE TABLE IF NOT EXISTS ChatModes (
                chat_id VARCHAR(255) NOT NULL,
                mode VARCHAR(255) NOT NULL,
                PRIMARY KEY (chat_id)
            )
        ''')

        db.commit()

def set_chat_mode(update, context, mode):
    if not check_admin(update, context):
        return
    chat_id = update.message.chat_id
    print('setting chat mode', chat_id, mode)
    with sqlite3.connect(DB_NAME) as db:
        db.execute('''
            INSERT OR REPLACE INTO ChatModes (chat_id, mode) VALUES (?, ?)
        ''', (chat_id, mode))

        db.commit()
    # reply to user
    update.message.reply_text(f'Now checklist will appear in reply only to messages starting with "todo" or "td" or "c "' if mode == 'todo' else \
                               'Now checklist will appear in reply to any message (expect starting with . or !)')

def get_chat_mode(chat_id):
    with sqlite3.connect(DB_NAME) as db:
        cursor = db.execute('''
            SELECT mode FROM ChatModes WHERE chat_id = ?
        ''', (chat_id,))

        row = cursor.fetchone()
        if not row:
            return None
        return row[0]

def cleanup_old_replies():
    # delete posts older then 1 year
    with sqlite3.connect(DB_NAME) as db:
        db.execute('''
            DELETE FROM Replies WHERE created_at < datetime('now', '-1 year')
        ''')

        db.commit()

def get_reply_by_message_id(message_id, chat_id) -> tuple:
    with sqlite3.connect(DB_NAME) as db:
        cursor = db.execute('''
            SELECT reply_and_chat_id, state FROM Replies WHERE message_and_chat_id = ?
        ''', (f"{chat_id}_{message_id}",))

        row = cursor.fetchone()
        if not row:
            return None, None
        return row[0], json.loads(row[1]) if row[1] else {}
        

def insert_reply(message_id, reply_id, chat_id):
    with sqlite3.connect(DB_NAME) as db:
        db.execute(
            '''
            INSERT INTO Replies (message_and_chat_id, reply_and_chat_id, state) VALUES (?, ?, ?)
            ''', 
            (f"{chat_id}_{message_id}", f"{chat_id}_{reply_id}", "{}")
        )

        db.commit()

def update_reply(reply_id, chat_id, state: dict):
    with sqlite3.connect(DB_NAME) as db:
        db.execute('''
            UPDATE Replies SET state = ? WHERE reply_and_chat_id = ?
        ''', 
        (json.dumps(state), f"{chat_id}_{reply_id}"))

        db.commit()



logger = logging.getLogger(__name__)

TOKEN = os.environ.get('KIWI_PLANIFIER_BOT')

if not TOKEN:
    print('TG_TOKEN not specified in env, please set TG_TOKEN with your bot token generated by @BotFather')
    exit(1)

async def button_click(update, context):
    query = update.callback_query
    await query.answer()

    if not query.message.reply_markup:
        print(f'no reply_markup for message_id {query.message.message_id} and chat_id {query.message.chat_id}')
        return

    new_keyboard = []
    state = {}

    for i, row in enumerate(query.message.reply_markup.inline_keyboard):
        old_button = row[0]
        btn_text = old_button.text.replace(f'{UNCHECK_CHAR} ', '').replace(f'{CHECK_CHAR} ', '')

        if query.data == f"toggle__{i}":
            checked = not old_button.text.startswith(CHECK_CHAR)
        else:
            checked = old_button.text.startswith(CHECK_CHAR)

        new_text = f"{CHECK_CHAR if checked else UNCHECK_CHAR} {btn_text}"
        new_keyboard.append([InlineKeyboardButton(new_text, callback_data=f"toggle__{i}")])
        state[btn_text] = checked

    # save state
    reply_id = query.message.message_id
    update_reply(reply_id, query.message.chat_id, state)

    # update the message with the new keyboard
    await context.bot.edit_message_text(
        chat_id=query.message.chat_id,
        message_id=query.message.message_id,
        text="Click to toggle",
        reply_markup=InlineKeyboardMarkup(new_keyboard)
    )


def md5hash(text):
    return hashlib.md5(text.encode('utf-8')).hexdigest()


TODO_MODE_REGEX = re.compile(r'^(todo|tobedo|td|tbd|tobedone|checklist|check |cl |c )\s?', re.IGNORECASE)

def check_admin(update, context):
    now_in_channel = update.message.chat.type == 'channel'
    now_in_group = update.message.chat.type == 'group'
    ia_am_admin = update.message.chat.get_member(context.bot.id).status in ['administrator', 'creator']

    if now_in_channel or now_in_group and not ia_am_admin:
        update.message.reply_text(f'Please promote me to admin in {update.message.chat.type} settings to enable me to generate checklists in replies. I need it because you added me to a {update.message.chat.type}, also you can use me in direct chat without promoting me')
        return False
    return True

def startBotPrompt(update, context):
    if check_admin(update, context):
        update.message.reply_text("""Hello! I am your checklist bot. I will reply to your messages with a checklist. You can click on each item to toggle it.
You can set the mode to "todo" with /only_todo command to make me reply only to messages starting with "todo" or "td" or "c " """)
        

def main() -> None:
    gen_db()
    cleanup_old_replies()

    app = Application.builder().token(TOKEN).build()

    app.add_handler(CallbackQueryHandler(button_click))
    app.add_handler(MessageHandler(~filters.COMMAND, echo))
    app.add_handler(CommandHandler('only_todo', lambda up, con: set_chat_mode(up, con, 'todo')))
    app.add_handler(CommandHandler('all', lambda up, con: set_chat_mode(up, con, 'all')))
    app.add_handler(CommandHandler('start', startBotPrompt))

    # Set bot commands
    async def set_commands(app):
        await app.bot.set_my_commands([
            BotCommand("only_todo", "Set mode to 'todo' messages"),
            BotCommand("all", "Set mode to any messages"),
            BotCommand("start", "Start the bot"),
        ])
    app.post_init = set_commands

    app.run_polling()

if __name__ == '__main__':
    main()