"""baseline

Revision ID: 6f29a6f53973
Revises: 
Create Date: 2026-08-19 16:07:21.453845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f29a6f53973'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('datetime_deadline', sa.DateTime(), nullable=True),
    sa.Column('datetime_done', sa.DateTime(), nullable=True),
    sa.Column('datetime_started', sa.DateTime(), nullable=True),
    sa.Column('datetime_completed', sa.DateTime(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('price_budget', sa.Float(), nullable=True),
    sa.Column('price_real', sa.Float(), nullable=True),
    sa.Column('people_count', sa.Integer(), nullable=True),
    sa.Column('template', sa.Boolean(), nullable=True),
    sa.Column('recuring', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('tag', sa.JSON(), nullable=True),
    sa.Column('time_slot', sa.String(length=50), nullable=True),
    sa.Column('periodicity', sa.String(length=50), nullable=True),
    sa.Column('time_estimate', sa.Integer(), nullable=True),
    sa.Column('extension', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('events',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('datetime_start', sa.DateTime(), nullable=False),
    sa.Column('datetime_end', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('guests', sa.JSON(), nullable=True),
    sa.Column('task', sa.Integer(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('price_budget', sa.Float(), nullable=True),
    sa.Column('price_real', sa.Float(), nullable=True),
    sa.Column('people_count', sa.Integer(), nullable=True),
    sa.Column('template', sa.Boolean(), nullable=True),
    sa.Column('recuring', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('extension', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['task'], ['tasks._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_events_google_event_id'), 'events', ['google_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_google_event_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('tasks')
    # ### end Alembic commands ###
